# Generated by Django 5.0.4 on 2024-04-21 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=9, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('total_time', models.IntegerField(null=True, verbose_name='Total Time')),
                ('total_duration', models.IntegerField(null=True, verbose_name='Expiry Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Code')),
                ('time_left', models.IntegerField(verbose_name='Time Left (Seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer', verbose_name='Customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.package', verbose_name='Package')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True, verbose_name='Time In')),
                ('time_out', models.DateTimeField(null=True, verbose_name='Time Out')),
                ('amount', models.IntegerField(null=True, verbose_name='Total Amount')),
                ('payment_method', models.CharField(choices=[('GCash', 'Paid with GCash'), ('Cash', 'Paid with cash'), ('Other', 'Other payment method')], max_length=20, verbose_name='Payment Method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer', verbose_name='Customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.package', verbose_name='Package')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
                ('used_pass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.pass', verbose_name='Used Pass')),
            ],
        ),
    ]
