# Generated by Django 5.0.4 on 2024-04-22 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_passes', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='package',
            field=models.ForeignKey(limit_choices_to={'type': 'prepaid'}, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.package', verbose_name='Package'),
        ),
    ]
